### PR TITLE
Release 0.4.0

### LINKED ISSUE #2: Implement signing of transactions with arbitrary length

### LINKED ISSUE #3: Enable signing of transactions required for smart contracts, state channels, and naming system

### PR DESCRIPTION
**Pull request by davidyuk**
closes #2 closes #3

We were not able to test in on Nano X because of the lack of hardware.

### CODE REVIEW

**Comment by thepiwo** [comment]
@TamtamHero how do we get this update merged?

**Comment by marc0olo** [comment]
@gre why is this still open? :-(

**Comment by marc0olo** [comment]
@TamtamHero can we got some reaction here?

**Comment by thepiwo** [comment]
or maybe @valpinkman can help?

**Pull request merged**
